import {createGame,applyAction,botAction,validateState} from '../dist/js/engine.js';
import {advancedActor} from '../dist/js/advanced.js';
import {chooseDifficultyAction} from '../dist/js/ai.js';
import {getScenarioOptions} from '../dist/js/scenarios.js';
import {writeFileSync,mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
const count=Number(process.env.AI_SEEDS??5),profiles=(process.env.AI_PROFILES??'basic').split(','),maxSteps=Number(process.env.AI_MAX_STEPS??1500),output=process.argv[2]??'docs/ai-balance-report.json';
const seeds=process.env.AI_SEED_LIST?process.env.AI_SEED_LIST.split(',').map(Number):[1,29,1986,2026,20261005,17,97,329,430,777].slice(0,count);
if(!seeds.length||seeds.some(seed=>!Number.isInteger(seed)||seed<1||seed>4294967295)||!Number.isInteger(maxSteps)||maxSteps<1||profiles.some(profile=>!['basic','advanced'].includes(profile)))throw new Error('Use valid nonzero 32-bit seeds, basic/advanced profiles, and a positive action cap.');
const pairs=[['easy','normal'],['easy','hard'],['normal','hard']];
const started=Date.now(),games=[];
for(const profile of profiles)for(const option of getScenarioOptions())for(const pair of pairs)for(const seed of seeds)for(const swapped of [false,true]){
  const sideDifficulty={invader:pair[swapped?1:0],resistance:pair[swapped?0:1]},runStarted=Date.now();
  let s=createGame({...option.config,profile,seed,controllers:Object.fromEntries(option.config.scenario.kingdoms.map(k=>[k.id,'ai']))}),steps=0,error=null,largestLegalDecisionMs=0,types={},kingdomActions={};
  try{while(s.phase!=='game-over'&&steps<maxSteps){const actor=advancedActor(s),k=s.kingdoms.find(k=>k.id===actor),difficulty=sideDifficulty[k?.side??'resistance'],decisionStarted=Date.now();const action=chooseDifficultyAction(s,difficulty,difficulty==='hard'?null:botAction(s));largestLegalDecisionMs=Math.max(largestLegalDecisionMs,Date.now()-decisionStarted);if(!action)throw new Error('No legal AI action in nonterminal state');types[action.type]=(types[action.type]??0)+1;kingdomActions[actor]=(kingdomActions[actor]??0)+1;s=applyAction(s,action);steps++;if(steps%30===0){const issues=validateState(s);if(issues.length)throw new Error(issues.join('; '));}}const issues=validateState(s);if(issues.length)throw new Error(issues.join('; '));}catch(e){error=String(e?.message??e);}
  const game={profile,scenario:option.id,seed,swapped,sideDifficulty,winner:s.winner,winnerDifficulty:s.winner?sideDifficulty[s.winner]:null,terminal:s.phase==='game-over',steps,elapsedMs:Date.now()-runStarted,largestLegalDecisionMs,error,actionCounts:types,kingdomActions,remainingKingdoms:s.kingdoms.filter(k=>!k.collapsed).map(k=>k.id),finalPhase:s.phase,finalActor:advancedActor(s),finalPending:s.advanced?.pending?.kind??s.pendingCombat?.stage??null,finalYear:s.year,finalSeason:s.season,finalActiveUnit:s.activeUnitId,finalRemainingMP:s.remainingMP,victoryReason:s.victoryReason};games.push(game);
  console.log(`${games.length} ${profile} ${option.id} seed=${seed} ${sideDifficulty.invader}/${sideDifficulty.resistance} ${game.terminal?game.winnerDifficulty:'TIMEOUT'} ${steps} actions ${game.elapsedMs}ms${error?' ERROR '+error:''}`);
  const matchups=Object.fromEntries(pairs.map(([a,b])=>{const relevant=games.filter(g=>Object.values(g.sideDifficulty).includes(a)&&Object.values(g.sideDifficulty).includes(b));return [a+'-vs-'+b,{played:relevant.length,wins:{[a]:relevant.filter(g=>g.winnerDifficulty===a).length,[b]:relevant.filter(g=>g.winnerDifficulty===b).length},invalid:relevant.filter(g=>g.error||!g.terminal).length}];}));
  const sideResults=Object.fromEntries(['invader','resistance'].map(side=>[side,Object.fromEntries(['easy','normal','hard'].map(d=>{const relevant=games.filter(g=>g.sideDifficulty[side]===d);return [d,{played:relevant.length,wins:relevant.filter(g=>g.winner===side).length}];}))]));
  const summary=Object.fromEntries(['easy','normal','hard'].map(d=>{const played=games.filter(g=>Object.values(g.sideDifficulty).includes(d));const wins=played.filter(g=>g.winnerDifficulty===d).length;return[d,{played:played.length,wins,winRate:played.length?wins/played.length:0}];}));
  mkdirSync(dirname(output),{recursive:true});writeFileSync(output,JSON.stringify({generatedAt:new Date().toISOString(),description:'Paired deterministic seeds, both side assignments, two original digital scenarios. Whole alliances use the same difficulty. These are self-play measurements, not proof of expert human strength or official campaign balance.',elapsedMs:Date.now()-started,maxSteps,tuningSeeds:[1,29],initiallyReservedAdditionalSeeds:[17,97,329,430,777].filter(seed=>seeds.includes(seed)),seedNote:'Additional seeds were initially reserved from tuning, then reused for final verification; they are not an untouched final holdout.',summary,matchups,sideResults,completed:games.filter(g=>g.terminal).length,errors:games.filter(g=>g.error).length,timeouts:games.filter(g=>!g.terminal&&!g.error).length,games},null,2)+'\n');
}
