import { hexes, unitDefinitions, scenario } from './content.js';
import type { Hex, HexEdge, ScenarioDefinition, UnitDefinition, GameConfig } from './engine.js';
import { validateContentPack } from './content-validation.js';
const el = <T extends HTMLElement>(id:string) => document.getElementById(id) as T;
const input = (id:string) => el<HTMLInputElement>(id);
const select = (id:string) => el<HTMLSelectElement>(id);
const svg = document.getElementById('map') as unknown as SVGSVGElement;
const world = document.getElementById('world') as unknown as SVGGElement;
let pack:GameConfig = structuredClone({hexes,unitDefinitions,scenario});
let selected:string|null=null;
let reference:string|null=null;
let referenceSize = {width:0,height:0};
let dragging=false;
let camera={x:0,y:0,w:1300,h:1100};
let start={x:0,y:0,cx:0,cy:0,hexId:null as string|null};
let activePointer:number|null=null;
const dirs=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
const colors:Record<string,string>={clear:'#cab78f',forest:'#526947',mountain:'#8b8270',swamp:'#748a78',sea:'#7199a6',coastal:'#82a6a0','major-river':'#87a9ad',lair:'#996b68'};
const radius=()=>Number(input('radius').value)||60;
const xy=(h:Hex)=>({x:radius()*1.5*h.q,y:radius()*Math.sqrt(3)*(h.r+h.q/2)});
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function notice(message:string,error=false){el('notice').textContent=message;el('notice').dataset.error=String(error);}
function fit(){const points=pack.hexes.map(xy);const pad=radius()*1.3;const minX=Math.min(...points.map(p=>p.x))-pad;const minY=Math.min(...points.map(p=>p.y))-pad;camera={x:minX,y:minY,w:Math.max(...points.map(p=>p.x))+pad-minX,h:Math.max(...points.map(p=>p.y))+pad-minY};render();}
function render(){svg.setAttribute('viewBox',`${camera.x} ${camera.y} ${camera.w} ${camera.h}`);let markup='';if(reference){const scale=Number(input('image-scale').value)||1;markup+=`<image href="${reference}" x="${Number(input('origin-x').value)}" y="${Number(input('origin-y').value)}" width="${referenceSize.width*scale}" height="${referenceSize.height*scale}" opacity="${Number(input('opacity').value)}"/>`;}
for(const h of pack.hexes){const p=xy(h),r=radius();const pts=Array.from({length:6},(_,i)=>{const a=i*60*Math.PI/180;return `${p.x+r*Math.cos(a)},${p.y+r*Math.sin(a)}`;}).join(' ');markup+=`<polygon class="hex ${h.id===selected?'selected':''}" data-id="${esc(h.id)}" points="${pts}" fill="${colors[h.terrain]}" ${h.prohibited?'stroke-dasharray="5 4"':''}/>`;markup+=`<text x="${p.x}" y="${p.y-14}" text-anchor="middle" font-size="11" fill="#322d25" pointer-events="none">${esc(h.id)}</text>`;if(h.settlement)markup+=`<text class="settlement" x="${p.x}" y="${p.y+16}" text-anchor="middle" pointer-events="none">${esc(h.settlement.name)}</text>`;if(h.mine)markup+=`<text x="${p.x}" y="${p.y+30}" text-anchor="middle" font-size="12" pointer-events="none">Mine</text>`;}
for(const h of pack.hexes){for(const [toId,edge] of Object.entries(h.edges??{})){if(h.id>toId)continue;const target=pack.hexes.find(t=>t.id===toId);if(!target)continue;const a=xy(h),b=xy(target);if(edge.road)markup+=`<path d="M${a.x},${a.y} L${b.x},${b.y}" stroke="#876342" stroke-width="3" stroke-dasharray="6 4" pointer-events="none"/>`;if(edge.river){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2,dx=(b.x-a.x)*.23,dy=(b.y-a.y)*.23;markup+=`<path d="M${mx-dy},${my+dx} L${mx+dy},${my-dx}" stroke="#3979a4" stroke-width="${edge.river===2?6:3}" pointer-events="none"/>`;}}}world.innerHTML=markup;}
function selectHex(id:string){selected=id;const h=pack.hexes.find(h=>h.id===id)!;el('hex-title').textContent=`${h.id} · q ${h.q}, r ${h.r} · ${h.terrain}`;input('prohibited').checked=!!h.prohibited;input('mine').checked=!!h.mine;input('settlement-name').value=h.settlement?.name??'';if(h.settlement?.loyalty&&!Array.from(select('loyalty').options).some(o=>o.value===h.settlement!.loyalty))select('loyalty').add(new Option(h.settlement.loyalty,h.settlement.loyalty));select('loyalty').value=h.settlement?.loyalty??'';select('fortification').value=String(h.settlement?.fortified??0);input('city').checked=!!h.settlement?.city;input('port').checked=!!h.settlement?.port;const neighbors=pack.hexes.filter(t=>dirs.some(([dq,dr])=>t.q===h.q+dq&&t.r===h.r+dr));select('neighbor').innerHTML=neighbors.map(n=>`<option value="${esc(n.id)}">${esc(n.id)} · ${esc(n.settlement?.name??n.terrain)}</option>`).join('');loadEdge();render();}
function loadEdge(){const h=pack.hexes.find(h=>h.id===selected),edge=h?.edges?.[select('neighbor').value]??{};input('road').checked=!!edge.road;select('river').value=String(edge.river??0);input('sea-edge').checked=!!edge.sea;input('coast-edge').checked=!!edge.coastal;}
svg.addEventListener('pointerdown',event=>{if(event.button!==0||activePointer!==null)return;activePointer=event.pointerId;start={x:event.clientX,y:event.clientY,cx:camera.x,cy:camera.y,hexId:(event.target as Element).closest('[data-id]')?.getAttribute('data-id')??null};dragging=false;svg.setPointerCapture(event.pointerId);});
svg.addEventListener('pointermove',event=>{if(activePointer!==event.pointerId)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)>6)dragging=true;if(dragging){const box=svg.getBoundingClientRect();camera.x=start.cx-dx*camera.w/box.width;camera.y=start.cy-dy*camera.h/box.height;svg.setAttribute('viewBox',`${camera.x} ${camera.y} ${camera.w} ${camera.h}`);}});
svg.addEventListener('pointerup',event=>{if(activePointer!==event.pointerId)return;activePointer=null;if(svg.hasPointerCapture(event.pointerId))svg.releasePointerCapture(event.pointerId);if(!dragging&&start.hexId){const h=pack.hexes.find(h=>h.id===start.hexId);if(h){const terrain=select('terrain').value;if(terrain!=='inspect')h.terrain=terrain as Hex['terrain'];selectHex(h.id);}}dragging=false;});
svg.addEventListener('pointercancel',event=>{if(activePointer!==event.pointerId)return;activePointer=null;dragging=false;if(svg.hasPointerCapture(event.pointerId))svg.releasePointerCapture(event.pointerId);});
svg.addEventListener('wheel',event=>{event.preventDefault();const factor=event.deltaY>0?1.13:.88;const box=svg.getBoundingClientRect(),fx=(event.clientX-box.left)/box.width,fy=(event.clientY-box.top)/box.height;camera.x+=camera.w*fx*(1-factor);camera.y+=camera.h*fy*(1-factor);camera.w*=factor;camera.h*=factor;render();},{passive:false});
el('save-hex').onclick=()=>{const h=pack.hexes.find(h=>h.id===selected);if(!h){notice('Select a hex first.',true);return;}h.mine=input('mine').checked;h.prohibited=input('prohibited').checked;const name=input('settlement-name').value.trim();if(name)h.settlement={...h.settlement,name,loyalty:select('loyalty').value||null,city:input('city').checked,port:input('port').checked,fortified:Number(select('fortification').value) as 0|1|2};else delete h.settlement;notice(`Updated ${h.id}.`);render();};
select('neighbor').onchange=loadEdge;
el('save-edge').onclick=()=>{const h=pack.hexes.find(h=>h.id===selected),to=pack.hexes.find(h=>h.id===select('neighbor').value);if(!h||!to){notice('Select a hex and adjacent neighbor first.',true);return;}const edge:HexEdge={};if(input('road').checked)edge.road=true;const river=Number(select('river').value);if(river)edge.river=river as 1|2;if(input('sea-edge').checked)edge.sea=true;if(input('coast-edge').checked)edge.coastal=true;(h.edges??={})[to.id]=edge;(to.edges??={})[h.id]={...edge};notice(`Updated reciprocal crossing ${h.id} ↔ ${to.id}.`);render();};
function updateEditors(){el<HTMLTextAreaElement>('scenario-json').value=JSON.stringify(pack.scenario,null,2);el<HTMLTextAreaElement>('units-json').value=JSON.stringify(pack.unitDefinitions,null,2);input('source').value=pack.scenario.source;}
el('map-tab').onclick=()=>{el('map-controls').classList.remove('hide');el('scenario-controls').classList.add('hide');};el('scenario-tab').onclick=()=>{updateEditors();el('map-controls').classList.add('hide');el('scenario-controls').classList.remove('hide');};
el('apply-scenario').onclick=()=>{try{const candidate=JSON.parse(el<HTMLTextAreaElement>('scenario-json').value) as ScenarioDefinition;pack=validateContentPack({version:1,...pack,scenario:candidate});notice('Scenario definition checked and applied.');}catch(e){notice(String(e),true);}};
el('apply-units').onclick=()=>{try{const candidate=JSON.parse(el<HTMLTextAreaElement>('units-json').value) as UnitDefinition[];pack=validateContentPack({version:1,...pack,unitDefinitions:candidate});notice('Unit inventory checked and applied.');}catch(e){notice(String(e),true);}};
function checked(){const candidate=structuredClone(pack);candidate.scenario.official=false;candidate.scenario.source=input('source').value.trim()||'User-authored map workshop pack; not an official campaign.';return validateContentPack({version:1,...candidate});}
el('validate').onclick=()=>{try{const p=checked();notice(`Valid pack: ${p.hexes.length} hexes, ${p.unitDefinitions.length} unit types, ${p.scenario.kingdoms.length} kingdoms. Validation checks structure and references; it cannot certify source fidelity.`);}catch(e){notice(String(e),true);}};
el('export').onclick=()=>{try{const p=checked();const blob=new Blob([JSON.stringify({version:1,...p},null,2)],{type:'application/json'});if(blob.size>20_000_000)throw new Error('Export exceeds 20 MB. Reduce embedded artwork before exporting.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='burning-banners-content-pack.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Exported checked content pack. Import it from the war table setup.');}catch(e){notice(String(e),true);}};
input('import').onchange=async()=>{const file=input('import').files?.[0];if(!file)return;try{if(file.size>20_000_000)throw new Error('Content pack exceeds 20 MB.');pack=validateContentPack(JSON.parse(await file.text()));selected=null;updateEditors();fit();notice('Imported checked content pack.');}catch(e){notice(String(e),true);}};
input('reference').onchange=()=>{const file=input('reference').files?.[0];if(!file)return;if(file.size>20_000_000){notice('Reference image exceeds 20 MB.',true);return;}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{reference=String(reader.result);referenceSize={width:img.width,height:img.height};render();notice('Reference opened locally. Calibrate size and origin, then review every terrain and crossing.');};img.src=String(reader.result);};reader.readAsDataURL(file);};
for(const id of ['radius','image-scale','origin-x','origin-y','opacity'])input(id).oninput=render;
el('clear-reference').onclick=()=>{reference=null;render();};el('fit').onclick=fit;
updateEditors();fit();
