import type {GameState,Hex,HexEdge} from './engine.js';
import type {TableOperation} from './tabletop.js';
import {cardById,monsters,isHero,stackIds,runtimeLimitations} from './advanced.js';
import {advancedCatalog} from './advanced-data.js';

export type TableTab='pieces'|'cards'|'map'|'campaign';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let fieldSerial=0;
const select=(name:string,label:string,options:{id:string;name:string}[],value?:string)=>{const id=`table-field-${fieldSerial++}`;return `<div class="table-field"><label for="${id}">${label}</label><select id="${id}" name="${name}">${options.map(o=>`<option value="${esc(o.id)}" ${o.id===value?'selected':''}>${esc(o.name)}</option>`).join('')}</select></div>`;};
const numeric=(name:string,label:string,value:number,min=0,max=1000)=>`<label>${label}<input name="${name}" type="number" value="${value}" min="${min}" max="${max}" required></label>`;
const check=(name:string,label:string,checked=false)=>`<label class="table-check"><input type="checkbox" name="${name}" ${checked?'checked':''}>${label}</label>`;
const submit=(title:string)=>`<button type="submit" class="secondary-button">${title}</button>`;
const form=(kind:string,title:string,body:string)=>`<form data-table-form="${kind}" class="table-form"><h3>${title}</h3>${body}<label>Rule / reason<input name="reason" value="Printed campaign setup / table ruling" maxlength="800" minlength="3" required></label>${submit(title)}</form>`;
export function renderTabletop(s:GameState,tab:TableTab,playerId:string,hexId:string|null,kingdomId:string,edgeTarget:string|null=null):string {
  fieldSerial=0;
  const a=s.advanced!,t=s.tabletop!,p=a.players.find(p=>p.id===playerId)!;
  const hexOptions=s.hexes.map(h=>({id:h.id,name:`${h.settlement?.name??h.id} · ${h.id}`}));
  const kingdomOptions=s.kingdoms.filter(k=>!k.collapsed).map(k=>({id:k.id,name:k.name}));
  const units=s.units.map(u=>({id:u.id,name:`${s.unitDefinitions.find(d=>d.id===u.defId)!.name} · ${u.hexId}`}));
  const supply=s.unitDefinitions.filter(d=>s.units.filter(u=>u.defId===d.id).length<d.count&&(d.kind!=='hero'||a.heroPools[d.kingdom]?.includes(d.id))).map(d=>({id:d.id,name:`${s.kingdoms.find(k=>k.id===d.kingdom)?.name} · ${d.name} (${d.count-s.units.filter(u=>u.defId===d.id).length} in supply)`}));
  const note=`<p class="table-note">Full tabletop keeps every physical card and counter available. Standard legal actions use the rules engine. These controls record human adjudications and setup changes in the briefing and replay. The computer uses automated effects; a table resolution pauses play until completed.</p>`;
  const review=t.review?`<section class="table-review" role="status"><strong>Resolve ${esc(cardById(t.review.cardId)!.name)} at the table</strong><p>${esc(cardById(t.review.cardId)!.summary)}</p><p>Use the controls below for targets, dice, costs, movement and modifiers. Complete the resolution when all players have made their choices.</p><button class="primary-button" data-command="table-complete">Complete card resolution</button></section>`:'';
  let body='';
  if(tab==='pieces')body=`<div class="table-grid">${form('place','Place a counter',select('defId','Counter',supply)+select('hexId','Hex',hexOptions,hexId??undefined)+check('weakened','Weakened side')+check('finished','Finished activation'))}${units.length?form('move','Relocate a unit',select('unitId','Unit',units)+select('hexId','Destination',hexOptions,hexId??undefined)+check('wholeStack','Move its entire stack',true))+form('unit','Update a unit',select('unitId','Unit',units)+select('status','Change',[{id:'ready',name:'Ready'},{id:'finished',name:'Finished activation'},{id:'weakened',name:'Weakened'},{id:'full',name:'Full strength'},{id:'eliminate',name:'Eliminate'},{id:'lock',name:'Lock Hero card'},{id:'unlock',name:'Unlock Hero card'}])):''}${form('monster','Place a Monster',select('defId','Monster',monsters.filter(m=>a.monsterPools[m.pool].includes(m.id)).map(m=>({id:m.id,name:m.name})))+select('hexId','Hex',hexOptions,hexId??undefined)+select('kingdomId','Commander',[{id:'',name:'Uncommanded'},...kingdomOptions])+check('lair','Lair Monster'))}${a.monsters.length?form('remove-monster','Remove a Monster',select('monsterId','Monster',a.monsters.map(m=>({id:m.id,name:`${monsters.find(d=>d.id===m.defId)!.name} · ${m.hexId}`})))+check('recycle','Return to pool (Slink Away); otherwise defeated')):''}${s.units.some(u=>!isHero(s,u))?form('enslave','Enslaved Hero marker',select('armyId','Army',units.filter(o=>!isHero(s,s.units.find(u=>u.id===o.id)!)))+check('release','Release Army / remove Enslaved Hero')):''}${form('roll','Roll table dice',select('sides','Dice',[{id:'6',name:'Light · d6'},{id:'8',name:'Heavy · d8'}])+numeric('count','Number of dice',1,1,20))}</div>`;
  if(tab==='cards'){
    const hand=a.hands[p.id],owned=a.owned[p.id];const heroes=s.units.filter(u=>isHero(s,u)&&p.kingdoms.includes(u.kingdom));
    body=`<p class="table-note">Private components of <strong>${esc(p.name)}</strong>. Pass the device before another player reveals their hand.</p><div class="table-card-list">${hand.map(id=>{const c=cardById(id)!;return `<article><h3>${esc(c.name)} <small>${esc(c.kind)}</small></h3><p>${esc(c.summary)}</p>${runtimeLimitations[id]?'<span class="table-badge">Human table resolution</span>':'<span class="table-badge automated">Automated effect available</span>'}<button class="secondary-button" data-table-card="${esc(id)}">Play & resolve at table</button></article>`;}).join('')||'<p>No cards in hand.</p>'}</div><div class="table-card-list">${heroes.map(u=>`<article><h3>${esc(cardById(u.defId)!.name)} · Hero Power</h3><p>${esc(cardById(u.defId)!.summary)}</p><button data-table-power="${esc(u.defId)}" class="secondary-button">Resolve Hero Power at table</button></article>`).join('')}</div><div class="table-grid">${form('draw','Draw cards',select('deck','Deck',[{id:'spells',name:'Spells'},{id:'treasures',name:'Treasures'},...p.kingdoms.map(id=>({id:`blessings-${id}`,name:`${s.kingdoms.find(k=>k.id===id)!.name} Blessings`}))])+numeric('count','Number of cards',1,1,10))}${[...hand,...owned].length?form('card','Move a card',select('cardId','Your card',[...hand,...owned].map(id=>({id,name:`${cardById(id)!.name}${owned.includes(id)?' · owned':' · hand'}`})))+select('zone','Destination',[{id:'discard',name:'Discard / sold Treasure'},{id:'owned',name:'Owned Treasure'},{id:'hand',name:'Private hand'},{id:'eliminated',name:'Eliminated Treasure'},{id:'removed',name:'Permanently removed'}])):''}${units.length?form('effect','Apply card modifiers',select('cardId','Source card',advancedCatalog.cards.map(c=>({id:c.id,name:c.name})),t.review?.cardId)+select('target','Target',[...units,...a.monsters.map(m=>({id:m.id,name:monsters.find(d=>d.id===m.defId)!.name})),...hexOptions])+numeric('light','Light dice',0,-20,20)+numeric('heavy','Heavy dice',0,-20,20)+numeric('movement','Movement',0,-20,20)+numeric('fortification','Fortification',0,-20,20)+`<label>Abilities (comma separated)<input name="abilities" placeholder="mage, flying, ranged, stealth"></label>`+select('duration','Duration',[{id:'activation',name:'Current activation'},{id:'turn',name:'Current kingdom turn'}])):''}</div>`;
  }
  if(tab==='map'){
    const h=s.hexes.find(h=>h.id===hexId)??s.hexes[0],set=h.settlement;
    const around=s.hexes.filter(v=>Math.max(Math.abs(h.q-v.q),Math.abs(h.r-v.r),Math.abs(h.q+h.r-v.q-v.r))===1);
    const to=around.find(v=>v.id===edgeTarget)??around[0],crossing=to?{...to.edges?.[h.id],...h.edges?.[to.id]}:{};
    body=`<p class="table-note">Select a hex on the map before opening Table controls, or choose one here. Map changes are table rulings. Reviewed source terrain and crossings are supplied; unresolved details are documented in the Maps reference.</p><label class="table-selector">Edit hex<select id="table-hex">${hexOptions.map(o=>`<option value="${esc(o.id)}" ${o.id===h.id?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label><div class="table-grid">${form('hex','Update hex',select('terrain','Terrain',['clear','forest','mountain','swamp','sea','coastal','major-river','lair'].map(id=>({id,name:id})),h.terrain)+check('coastal','Coastal hex',h.coastal)+check('majorRiver','Major River course',h.majorRiver)+check('mine','Mine',h.mine)+check('prohibited','Prohibited',h.prohibited)+`<label>Settlement name<input name="settlement" value="${esc(set?.name)}" maxlength="100"></label>`+select('loyalty','Printed loyalty',[{id:'',name:'Neutral'},...kingdomOptions,...['assassins-guild','mara-mitai','night','oathborn','fjordland','empire','orcs','goblins'].filter(id=>!kingdomOptions.some(k=>k.id===id)).map(id=>({id,name:id==='assassins-guild'?'Assassins Guild':id==='mara-mitai'?'Mara Mitai':id}))],set?.loyalty??'')+numeric('fortified','Fortification',set?.fortified??0,0,2)+check('city','City',set?.city)+check('port','Port',set?.port)+select('wilderness','Settlement wilderness',[{id:'',name:'None'},{id:'forest',name:'Forest'},{id:'mountain',name:'Mountain'}],set?.wilderness??'')+select('entry','Entry area',[{id:'',name:'None'},...kingdomOptions],h.entry??''))}${set?form('marker','Set a marker',`<input type="hidden" name="hexId" value="${esc(h.id)}">`+select('marker','Marker',[{id:'control',name:'Control'},{id:'coven',name:'Secret Coven (Night)'},{id:'razed',name:'Razed'},{id:'clear',name:'Remove all markers'}])+select('kingdomId','Control owner',kingdomOptions)):''}${around.length?form('edge','Update a crossing',select('to','Adjacent hex',around.map(v=>({id:v.id,name:v.settlement?.name??v.id})),to.id)+check('road','Road',crossing.road)+select('river','River',[{id:'0',name:'None'},{id:'1',name:'Minor'},{id:'2',name:'Major'}],String(crossing.river??0))+check('sea','Sea edge',crossing.sea)+check('coastal','Coastal edge',crossing.coastal)+check('waterway','Shipping along Major River course',crossing.waterway)):''}</div>`;
  }
  if(tab==='campaign'){
    const k=s.kingdoms.find(k=>k.id===kingdomId&&!k.collapsed)??s.kingdoms.find(k=>!k.collapsed)!;
    body=`<label class="table-selector">Kingdom ledger<select id="table-kingdom">${kingdomOptions.map(o=>`<option value="${esc(o.id)}" ${o.id===k.id?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label><div class="table-grid">${form('resource','Update kingdom ledger',`<input type="hidden" name="kingdomId" value="${esc(k.id)}">`+numeric('gold','Gold',k.gold,0,1000000)+numeric('income','Income',k.income,0,10000)+numeric('revolt','Imperial revolt',k.revolt??0,0,19)+numeric('controlLimit','Printed control-counter supply',k.controlLimit??100,0,200))}${form('clock','Set date & active kingdom',select('kingdomId','Kingdom',kingdomOptions,s.currentKingdom)+numeric('year','Year',s.year,s.scenario.startYear,s.scenario.endYear)+select('season','Season',[{id:'0',name:'Spring'},{id:'1',name:'Summer'},{id:'2',name:'Autumn'}],String(s.season))+select('phase','Phase',[{id:'income-actions',name:'Income actions'},{id:'activation',name:'Activation'}],s.phase))}${form('victory','Adjudicate scenario victory',select('side','Winning alliance',[{id:'invader',name:'Invaders'},{id:'resistance',name:'Resistance'}])+`<label>Printed victory condition / result<textarea name="victoryReason" maxlength="800" required placeholder="Explain how the scenario victory condition was met"></textarea></label>`)}${form('campaign','Update campaign rules',`<label>Campaign name<input name="name" value="${esc(s.scenario.name)}" maxlength="100" required></label><label>Setup source & victory notes<textarea name="source" maxlength="2000">${esc(t.setupSource)}</textarea></label>${s.scenario.turnOrder.map((id,i)=>select('turn-'+i,'Turn '+(i+1),kingdomOptions,id)).join('')}${s.kingdoms.map(k=>select('side-'+k.id,k.name+' alliance',[{id:'invader',name:'Invaders'},{id:'resistance',name:'Resistance'}],k.side)).join('')}${check('manualVictory','Adjudicate victory from the printed scenario',t.manualVictory)}${select('objectiveType','Automated objective',[{id:'survival',name:'Invader survival at deadline'},{id:'control',name:'Control the selected Settlements'}],s.scenario.objective.type)}${select('objectiveKingdom','Scoring kingdom',[{id:'',name:'Invader alliance'},...kingdomOptions],s.scenario.objective.kingdom??'')}<label>Objective hex IDs (comma separated)<input name="objectiveHexes" value="${esc(s.scenario.objective.hexIds.join(', '))}"></label>${numeric('objectiveCount','Control count',s.scenario.objective.count,0,5000)}${check('deadlineOnly','Check only at campaign deadline',s.scenario.objective.deadlineOnly??true)}`)}${form('note','Record a table ruling',`<label>Ruling<textarea name="text" maxlength="800" required></textarea></label>`)}</div><details class="table-rulings"><summary>Table rulings (${t.rulings.length})</summary><ol>${[...t.rulings,...t.privateRulings?.[p.id]??[]].slice(-20).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details>`;
  }
  return `${note}<label class="table-selector">Pass table controls to<select id="table-seat">${a.players.map(x=>`<option value="${esc(x.id)}" ${x.id===playerId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${review}${a.pending?.kind==='hit'?'<p class="table-note">If a table effect prevented the next allocated hit, apply the rescue or marker removal, then consume that hit.</p><button class="secondary-button" data-command="table-consume-hit">Consume one prevented hit</button>':''}<nav class="table-tabs" aria-label="Table controls">${(['pieces','cards','map','campaign'] as const).map(id=>`<button data-table-tab="${id}" class="${id===tab?'active':''}">${id==='pieces'?'Counters & dice':id==='cards'?'Private cards':id==='map'?'Map & markers':'Campaign ledger'}</button>`).join('')}</nav>${body}`;
}
export function tableOperationFromForm(form:HTMLFormElement,s:GameState,playerId:string,hexId:string|null):TableOperation {
  const data=new FormData(form),str=(key:string)=>String(data.get(key)??''),n=(key:string)=>Number(str(key)),yes=(key:string)=>data.get(key)==='on';
  const kind=form.dataset.tableForm;
  if(kind==='enslave')return {kind,armyId:str('armyId'),release:yes('release')};
  if(kind==='campaign')return {kind,name:str('name'),source:str('source'),turnOrder:s.kingdoms.map((_,i)=>str('turn-'+i)),alliances:Object.fromEntries(s.kingdoms.map(k=>[k.id,str('side-'+k.id) as 'invader'|'resistance'])),manualVictory:yes('manualVictory'),objective:{type:str('objectiveType') as 'control'|'survival',hexIds:str('objectiveHexes').split(',').map(x=>x.trim()).filter(Boolean),count:n('objectiveCount'),deadlineOnly:yes('deadlineOnly'),...(str('objectiveKingdom').trim()?{kingdom:str('objectiveKingdom').trim()}:{})}};
  if(kind==='place')return {kind,defId:str('defId'),hexId:str('hexId'),weakened:yes('weakened'),finished:yes('finished')};
  if(kind==='move')return {kind,unitId:str('unitId'),hexId:str('hexId'),wholeStack:yes('wholeStack')};
  if(kind==='unit')return {kind,unitId:str('unitId'),status:str('status') as Extract<TableOperation,{kind:'unit'}>['status']};
  if(kind==='monster')return {kind,defId:str('defId'),hexId:str('hexId'),kingdomId:str('kingdomId')||null,lair:yes('lair')};
  if(kind==='remove-monster')return {kind,monsterId:str('monsterId'),recycle:yes('recycle')};
  if(kind==='draw')return {kind,playerId,deck:str('deck'),count:n('count')};
  if(kind==='card')return {kind,playerId,cardId:str('cardId'),zone:str('zone') as Extract<TableOperation,{kind:'card'}>['zone']};
  if(kind==='resource')return {kind,kingdomId:str('kingdomId'),gold:n('gold'),income:n('income'),revolt:n('revolt'),controlLimit:n('controlLimit')};
  if(kind==='roll')return {kind,sides:n('sides') as 6|8,count:n('count')};
  if(kind==='marker')return {kind,hexId:str('hexId'),marker:str('marker') as Extract<TableOperation,{kind:'marker'}>['marker'],kingdomId:str('kingdomId')};
  if(kind==='clock')return {kind,kingdomId:str('kingdomId'),year:n('year'),season:n('season') as 0|1|2,phase:str('phase') as 'activation'|'income-actions'};
  if(kind==='victory')return {kind,side:str('side') as 'invader'|'resistance',reason:str('victoryReason')};
  if(kind==='note')return {kind,text:str('text')};
  if(kind==='effect')return {kind,cardId:str('cardId'),target:str('target'),light:n('light'),heavy:n('heavy'),movement:n('movement'),fortification:n('fortification'),abilities:str('abilities').split(',').map(x=>x.trim()).filter(Boolean),duration:str('duration') as 'activation'|'turn'};
  if(kind==='hex'){
    const original=s.hexes.find(h=>h.id===hexId)??s.hexes[0],h:Hex={...original,terrain:str('terrain') as Hex['terrain'],coastal:yes('coastal'),majorRiver:yes('majorRiver'),mine:yes('mine'),prohibited:yes('prohibited')};
    if(str('settlement').trim())h.settlement={name:str('settlement').trim(),loyalty:str('loyalty')||null,city:yes('city'),port:yes('port'),fortified:n('fortified') as 0|1|2,...(str('wilderness')?{wilderness:str('wilderness') as 'forest'|'mountain'}:{})};else delete h.settlement;
    if(str('entry'))h.entry=str('entry');else delete h.entry;return {kind,hex:h};
  }
  if(kind==='edge'){
    const edge:HexEdge={};if(yes('road'))edge.road=true;if(n('river'))edge.river=n('river') as 1|2;if(yes('sea'))edge.sea=true;if(yes('coastal'))edge.coastal=true;if(yes('waterway'))edge.waterway=true;return {kind,from:hexId??s.hexes[0].id,to:str('to'),edge};
  }
  throw new Error('Choose a table operation.');
}
export function renderTableBuilder():string {
  return `<p>Start with all six kingdoms, every card, Hero and Monster, private hands, seeded dice, local saves and the campaign replay. Enter the opening from your Campaign Book using Table controls, then play with normal legal actions or recorded table adjudications.</p><p class="table-note">These boards include source-reviewed terrain, settlement characteristics and joins. The Maps reference lists crossings that still need review. Custom setup and victory conditions use table adjudication.</p><form id="table-builder" class="table-form"><label>Campaign name<input name="name" value="My Burning Banners campaign" required maxlength="100"></label><fieldset><legend>Boards</legend>${advancedCatalog.maps.boards.map(b=>check(`board-${b.id}`,b.name,b.id==='wildlands')).join('')}</fieldset>${numeric('startYear','Start year',1,1,10000)}${numeric('endYear','End year',10,1,10000)}<label>Setup source / victory notes<textarea name="source" maxlength="2000" placeholder="Campaign number, starting gold, alliances, turn order and special victory conditions"></textarea></label><button class="primary-button" type="submit">Create full tabletop</button></form>`;
}
